export const baseIncome = {
  item1: 0.1,
  item2: 0.5,
  item3: 4,
  item4: 10,
  item5: 40,
  item6: 100,
  item7: 400,
  item8: 6666,
  item9: 98765,
  item10: 999999,
};

export const basePrice = {
  item1: 15,
  item2: 100,
  item3: 500,
  item4: 3000,
  item5: 10000,
  item6: 40000,
  item7: 200000,
  item8: 1666666,
  item9: 123456789,
  item10: 3999999999,
};

export const startingValues = {
  buyMultiplier: 1,
  earnings: 0,
  money: 50,
  items: [
    {
      baseIncome: baseIncome.item1,
      bonusMultiplier: 1,
      cost: basePrice.item1,
      count: 0,
      income: 0,
      name: "Item 1",
    },
    {
      baseIncome: baseIncome.item2,
      bonusMultiplier: 1,
      cost: basePrice.item2,
      count: 0,
      income: 0,
      name: "Item 2",
    },
    {
      baseIncome: baseIncome.item3,
      bonusMultiplier: 1,
      cost: basePrice.item3,
      count: 0,
      income: 0,
      name: "Item 3",
    },
    {
      baseIncome: baseIncome.item4,
      bonusMultiplier: 1,
      cost: basePrice.item4,
      count: 0,
      income: 0,
      name: "Item 4",
    },
    {
      baseIncome: baseIncome.item5,
      bonusMultiplier: 1,
      cost: basePrice.item5,
      count: 0,
      income: 0,
      name: "Item 5",
    },
    {
      baseIncome: baseIncome.item6,
      bonusMultiplier: 1,
      cost: basePrice.item6,
      count: 0,
      income: 0,
      name: "Item 6",
    },
    {
      baseIncome: baseIncome.item7,
      bonusMultiplier: 1,
      cost: basePrice.item7,
      count: 0,
      income: 0,
      name: "Item 7",
    },
    {
      baseIncome: baseIncome.item8,
      bonusMultiplier: 1,
      cost: basePrice.item8,
      count: 0,
      income: 0,
      name: "Item 8",
    },
    {
      baseIncome: baseIncome.item9,
      bonusMultiplier: 1,
      cost: basePrice.item9,
      count: 0,
      income: 0,
      name: "Item 9",
    },
    {
      baseIncome: baseIncome.item10,
      bonusMultiplier: 1,
      cost: basePrice.item10,
      count: 0,
      income: 0,
      name: "Item 10",
    },
  ],
};
